on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://taniguchi-kyoichi.com/feed/'
          file: 'README.md'
          start_flag: "<!-- personal feed start -->"
          end_flag: "<!-- personal feed end -->"
      - if: ${{ steps.feed.outputs.changed == true }}
        uses: sarisia/actions-commit@master
