on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://taniguchi-kyoichi.com/feed/'
          file: 'README.md'
          start_flag: "<!-- personal feed start -->"
          end_flag: "<!-- personal feed end -->"
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://taniguchi-kyoichi.com/tech/feed/'
          file: 'README.md'
          start_flag: "<!-- tech feed start -->"
          end_flag: "<!-- tech feed end -->"
      - uses: sarisia/actions-readme-feed@v1
        with:
          url: 'https://www.youtube.com/feeds/videos.xml?playlist_id=PLBpEsYBOVBHQXLC_OWHPXAjVL6H5Bu4wU'
          file: 'README.md'
          start_flag: "<!-- youtube feed start -->"
          end_flag: "<!-- youtube feed end -->"
      - uses: sarisia/actions-commit@master
